services:
  - type: web
    name: pet-trading-api
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MONGODB_URL
        scope: build,runtime
        sync: false
      - key: API_SECRET
        scope: build,runtime
        sync: false
      - key: LOG_LEVEL
        value: INFO
        scope: build,runtime
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
