services:
  - type: web
    name: pet-trading-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port 8000
    autoDeploy: true
